
# LINEAR REGRESSION
## With y =2x+1

In [7]:

N =10
D_in =1
D_out =1

import torch
X = torch.randn(N, D_in)

true_W = torch.tensor([[2.0]])
true_b = torch.tensor([1.0])
y_true =X @ true_W + true_b +torch.randn(N, D_out) *0.1


In [8]:
W =torch.randn(D_in, D_out, requires_grad=True)
b =torch.randn(D_out, requires_grad=True)

print("Initial W:", W)
print("Initial b:", b)

Initial W: tensor([[-0.5488]], requires_grad=True)
Initial b: tensor([-0.1864], requires_grad=True)


In [16]:
y_hat =X @ W + b



# Backward_Pass

In [18]:
error =y_hat - y_true
squared_error =error **2
loss =squared_error.mean()
print("Initial loss:", loss.item())

Initial loss: 12.816129684448242


In [19]:
loss.backward()

In [20]:
print(f"Gradient of W: {W.grad}")
print(f"Gradient of b: {b.grad}")

Gradient of W: tensor([[-8.4301]])
Gradient of b: tensor([-3.3288])


# theta t+1 = theta - n.deltaL

In [22]:
learning_rate =0.01
w_new = W - learning_rate * W.grad
b_new = b - learning_rate * b.grad

In [25]:
epochs =100

W,b = torch.randn(1,1, requires_grad=True), torch.randn(1, requires_grad=True)

for epoch in range(epochs):
    y_hat =X @ W + b
    loss =((y_hat - y_true) **2).mean()
    loss.backward()
    
    with torch.no_grad():
        W -= learning_rate * W.grad
        b -= learning_rate * b.grad
        
        W.grad.zero_()
        b.grad.zero_()

    if epoch %10 ==0:
        print(f"Epoch {epoch}, Loss: {loss.item()} , W: {W.item()}, b: {b.item()}")
print("Trained W:", W)
print("Trained b:", b)


Epoch 0, Loss: 32.40823745727539 , W: -1.9334726333618164, b: -0.8306364417076111
Epoch 10, Loss: 16.893451690673828 , W: -0.808921217918396, b: -0.3841031789779663
Epoch 20, Loss: 8.826432228088379 , W: -0.003927052021026611, b: -0.04750223085284233
Epoch 30, Loss: 4.625819206237793 , W: 0.5718881487846375, b: 0.20730990171432495
Epoch 40, Loss: 2.4343700408935547 , W: 0.983415961265564, b: 0.40105509757995605
Epoch 50, Loss: 1.2883105278015137 , W: 1.2772356271743774, b: 0.5490328073501587
Epoch 60, Loss: 0.6870808005332947 , W: 1.4867712259292603, b: 0.6625723242759705
Epoch 70, Loss: 0.37041163444519043 , W: 1.6359976530075073, b: 0.7500903010368347
Epoch 80, Loss: 0.2027774155139923 , W: 1.7421047687530518, b: 0.8178608417510986
Epoch 90, Loss: 0.1134740486741066 , W: 1.8174123764038086, b: 0.8705786466598511
Trained W: tensor([[1.8662]], requires_grad=True)
Trained b: tensor([0.9081], requires_grad=True)


# Using nn.linear module

In [26]:
D_in =1
D_out =1

linear_layer =torch.nn.Linear(D_in, D_out)

print("Initial layer weight:", linear_layer.weight)
print("Initial layer bias:", linear_layer.bias)

y_hat = linear_layer(X)

print("Output y_hat:", y_hat)

Initial layer weight: Parameter containing:
tensor([[0.5741]], requires_grad=True)
Initial layer bias: Parameter containing:
tensor([-0.7549], requires_grad=True)
Output y_hat: tensor([[-0.2602],
        [-0.9104],
        [-1.1228],
        [-0.4647],
        [-1.5265],
        [-1.6609],
        [-0.0553],
        [-0.3987],
        [ 0.8501],
        [-1.0823]], grad_fn=<AddmmBackward0>)


In [27]:
relu =torch.nn.ReLU()
sample_data =torch.tensor([[-1.0, 0.0, 1.0],
                           [2.0, -3.0, 4.0]])
activated_data =relu(sample_data)

print("Input data:\n", sample_data)
print("Activated data:\n", activated_data)

Input data:
 tensor([[-1.,  0.,  1.],
        [ 2., -3.,  4.]])
Activated data:
 tensor([[0., 0., 1.],
        [2., 0., 4.]])


In [28]:
gelu =torch.nn.GELU()
sample_data =torch.tensor([[-1.0, 0.0, 1.0],
                            [2.0, -3.0, 4.0]])  
activated_data =gelu(sample_data)
print("Input data:\n", sample_data)
print("GELU Activated data:\n", activated_data)


Input data:
 tensor([[-1.,  0.,  1.],
        [ 2., -3.,  4.]])
GELU Activated data:
 tensor([[-0.1587,  0.0000,  0.8413],
        [ 1.9545, -0.0040,  3.9999]])


In [29]:
softmax =torch.nn.Softmax(dim=1)

logits =torch.tensor([[1.0, 2.0, 3.0],
                        [1.0, 3.0, 2.0]])

probabilities =softmax(logits)
print("Logits:\n", logits)
print("Probabilities after Softmax:\n", probabilities)


Logits:
 tensor([[1., 2., 3.],
        [1., 3., 2.]])
Probabilities after Softmax:
 tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.6652, 0.2447]])


In [30]:
vocab_size =10
embedding_dim =3

embedding_layer =torch.nn.Embedding(vocab_size, embedding_dim)

input_ids =torch.tensor([0, 2, 4, 7])
word_vectors =embedding_layer(input_ids)


In [32]:
norm_layer =torch.nn.LayerNorm(normalized_shape=embedding_dim)
input_features =torch.randn(2, 3)
normalized_features =norm_layer(input_features)

print(f"mean (should be close to 0): {normalized_features.mean(dim=-1)}")
print(f"std (should be close to 1): {normalized_features.std(dim=-1)} ")

mean (should be close to 0): tensor([-3.9736e-08,  3.9736e-08], grad_fn=<MeanBackward1>)
std (should be close to 1): tensor([1.2247, 1.2247], grad_fn=<StdBackward0>) 


In [33]:
dropout_layer =torch.nn.Dropout(p=0.5)
input_data =torch.randn(4, 5)

dropout_layer.train()
output_during_training = dropout_layer(input_data)

dropout_layer.eval()
output_during_evaluation = dropout_layer(input_data)

# Using TORCH.NN

In [36]:
import torch.nn as nn

class LinearRegressionModel(nn.Module):
    def __init__(self, input_dim, output_dim):
        super().__init__()
        self.linear_layer =nn.Linear(input_dim, output_dim)
    
    def forward(self, x):
        return self.linear_layer(x)
model =LinearRegressionModel(input_dim =1, output_dim =1)

In [37]:
print("Model Architecture:\n", model)


Model Architecture:
 LinearRegressionModel(
  (linear_layer): Linear(in_features=1, out_features=1, bias=True)
)


In [38]:
import torch.optim as optim

learning_rate =0.01

optimizer =optim.Adam(model.parameters(), lr=learning_rate)

loss_fn =torch.nn.MSELoss()

In [43]:
epoch =100

for epoch in range(epoch):
    y_hat =model(X)

    loss =loss_fn(y_hat, y_true)
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    if epoch %10 ==0:
        print(f"Epoch {epoch}, Loss: {loss.item()}")
        

Epoch 0, Loss: 5.073929786682129
Epoch 10, Loss: 4.348869323730469
Epoch 20, Loss: 3.6908199787139893
Epoch 30, Loss: 3.1044976711273193
Epoch 40, Loss: 2.590311288833618
Epoch 50, Loss: 2.1453185081481934
Epoch 60, Loss: 1.7645232677459717
Epoch 70, Loss: 1.4419195652008057
Epoch 80, Loss: 1.1711515188217163
Epoch 90, Loss: 0.9458969235420227
